version: "2.1"
services:
  roulette:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      roulette-db:
        condition: service_healthy
  roulette-db:
    image: "redis:alpine"
    command: redis-server
    ports:
       - "6379:6379"
    volumes:
       - $PWD/redis-data:/var/lib/redis
        - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
  
    environment:
       - REDIS_REPLICATION_MODE=master
 
